name: CI and Docker Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-test-build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Check Formatting
        run: bunx prettier --check "src/**/*.{ts,tsx,js,jsx,json,md}"

      - name: Run Tests
        run: bun run test:run

      - name: Build Project
        run: bun run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/driver-license-management:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/driver-license-management:${{ github.sha }}
